#!/usr/bin/env bash
# Sync .agents/skills → .claude/skills so Claude Code auto-discovers project skills.
# Single source of truth is .agents/skills/<name>/SKILL.md — never edit .claude/skills directly.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
src="$repo_root/.agents/skills"
dst="$repo_root/.claude/skills"

rm -rf "$dst"
mkdir -p "$dst"

for skill_dir in "$src"/*/; do
  name="$(basename "$skill_dir")"
  if [[ -f "$skill_dir/SKILL.md" ]]; then
    mkdir -p "$dst/$name"
    cp "$skill_dir/SKILL.md" "$dst/$name/SKILL.md"
    cat > "$dst/$name/README.md" <<EOF
<!-- AUTO-GENERATED — do not edit this file directly.
     Source: .agents/skills/$name/SKILL.md
     Regenerate: make sync-skills  (runs automatically via pre-commit hook) -->
EOF
  fi
done

printf "sync-skills: synced %s skills to %s\n" \
  "$(find "$dst" -name 'SKILL.md' | wc -l | tr -d ' ')" \
  ".claude/skills/"
