name: Setup Labels

on:
  workflow_dispatch:

permissions:
  issues: write

env:
  PROTO_VERSION: "0.55.4"

jobs:
  create-labels:
    name: Create Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1

      - name: Setup toolchain
        uses: moonrepo/setup-toolchain@v0.6.4
        with:
          proto-version: ${{ env.PROTO_VERSION }}
          auto-install: true

      - name: Bootstrap repository labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          export REPO="${REPO}"
          moon run repo:issue-setup-labels
